/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BehaviourRouteImport } from './routes/behaviour'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as FaceRecognitionRouteImport } from './routes/face-recognition'
import { Route as FootfallRouteImport } from './routes/footfall'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as LiveAnalyticsRouteImport } from './routes/live-analytics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoodDetectionRouteImport } from './routes/mood-detection'
import { Route as ObjectDetectionRouteImport } from './routes/object-detection'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SiteManagementRouteImport } from './routes/site-management'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BehaviourRoute = BehaviourRouteImport.update({
  id: '/behaviour',
  path: '/behaviour',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceRecognitionRoute = FaceRecognitionRouteImport.update({
  id: '/face-recognition',
  path: '/face-recognition',
  getParentRoute: () => rootRouteImport,
} as any)
const FootfallRoute = FootfallRouteImport.update({
  id: '/footfall',
  path: '/footfall',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveAnalyticsRoute = LiveAnalyticsRouteImport.update({
  id: '/live-analytics',
  path: '/live-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodDetectionRoute = MoodDetectionRouteImport.update({
  id: '/mood-detection',
  path: '/mood-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectDetectionRoute = ObjectDetectionRouteImport.update({
  id: '/object-detection',
  path: '/object-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteManagementRoute = SiteManagementRouteImport.update({
  id: '/site-management',
  path: '/site-management',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/behaviour': typeof BehaviourRoute
  '/cameras': typeof CamerasRoute
  '/face-recognition': typeof FaceRecognitionRoute
  '/footfall': typeof FootfallRoute
  '/identity': typeof IdentityRoute
  '/live-analytics': typeof LiveAnalyticsRoute
  '/login': typeof LoginRoute
  '/mood-detection': typeof MoodDetectionRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/settings': typeof SettingsRoute
  '/site-management': typeof SiteManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/behaviour': typeof BehaviourRoute
  '/cameras': typeof CamerasRoute
  '/face-recognition': typeof FaceRecognitionRoute
  '/footfall': typeof FootfallRoute
  '/identity': typeof IdentityRoute
  '/live-analytics': typeof LiveAnalyticsRoute
  '/login': typeof LoginRoute
  '/mood-detection': typeof MoodDetectionRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/settings': typeof SettingsRoute
  '/site-management': typeof SiteManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/behaviour': typeof BehaviourRoute
  '/cameras': typeof CamerasRoute
  '/face-recognition': typeof FaceRecognitionRoute
  '/footfall': typeof FootfallRoute
  '/identity': typeof IdentityRoute
  '/live-analytics': typeof LiveAnalyticsRoute
  '/login': typeof LoginRoute
  '/mood-detection': typeof MoodDetectionRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/settings': typeof SettingsRoute
  '/site-management': typeof SiteManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/behaviour'
    | '/cameras'
    | '/face-recognition'
    | '/footfall'
    | '/identity'
    | '/live-analytics'
    | '/login'
    | '/mood-detection'
    | '/object-detection'
    | '/settings'
    | '/site-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/behaviour'
    | '/cameras'
    | '/face-recognition'
    | '/footfall'
    | '/identity'
    | '/live-analytics'
    | '/login'
    | '/mood-detection'
    | '/object-detection'
    | '/settings'
    | '/site-management'
  id:
    | '__root__'
    | '/'
    | '/behaviour'
    | '/cameras'
    | '/face-recognition'
    | '/footfall'
    | '/identity'
    | '/live-analytics'
    | '/login'
    | '/mood-detection'
    | '/object-detection'
    | '/settings'
    | '/site-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BehaviourRoute: typeof BehaviourRoute
  CamerasRoute: typeof CamerasRoute
  FaceRecognitionRoute: typeof FaceRecognitionRoute
  FootfallRoute: typeof FootfallRoute
  IdentityRoute: typeof IdentityRoute
  LiveAnalyticsRoute: typeof LiveAnalyticsRoute
  LoginRoute: typeof LoginRoute
  MoodDetectionRoute: typeof MoodDetectionRoute
  ObjectDetectionRoute: typeof ObjectDetectionRoute
  SettingsRoute: typeof SettingsRoute
  SiteManagementRoute: typeof SiteManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behaviour': {
      id: '/behaviour'
      path: '/behaviour'
      fullPath: '/behaviour'
      preLoaderRoute: typeof BehaviourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-recognition': {
      id: '/face-recognition'
      path: '/face-recognition'
      fullPath: '/face-recognition'
      preLoaderRoute: typeof FaceRecognitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footfall': {
      id: '/footfall'
      path: '/footfall'
      fullPath: '/footfall'
      preLoaderRoute: typeof FootfallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-analytics': {
      id: '/live-analytics'
      path: '/live-analytics'
      fullPath: '/live-analytics'
      preLoaderRoute: typeof LiveAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood-detection': {
      id: '/mood-detection'
      path: '/mood-detection'
      fullPath: '/mood-detection'
      preLoaderRoute: typeof MoodDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object-detection': {
      id: '/object-detection'
      path: '/object-detection'
      fullPath: '/object-detection'
      preLoaderRoute: typeof ObjectDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-management': {
      id: '/site-management'
      path: '/site-management'
      fullPath: '/site-management'
      preLoaderRoute: typeof SiteManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BehaviourRoute: BehaviourRoute,
  CamerasRoute: CamerasRoute,
  FaceRecognitionRoute: FaceRecognitionRoute,
  FootfallRoute: FootfallRoute,
  IdentityRoute: IdentityRoute,
  LiveAnalyticsRoute: LiveAnalyticsRoute,
  LoginRoute: LoginRoute,
  MoodDetectionRoute: MoodDetectionRoute,
  ObjectDetectionRoute: ObjectDetectionRoute,
  SettingsRoute: SettingsRoute,
  SiteManagementRoute: SiteManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
